---
- name: Executar META-PRE-DOMINIO
  hosts: all
  gather_facts: false

  tasks:
    - name: Rodar script META-PRE-DOMINIO.bat
      ansible.windows.win_shell: |
        cmd.exe /c "C:\Apos_colocar_no_dominio\META-POS-DOMINIO\META-PRE-DOMINIO.bat"
      args:
        executable: cmd
